base_commit: cffd4e0f86fefd4802349a9f9b19ed70934ea354
created_at: '2020-12-12T18:18:38Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
- SWE-bench/SWE-bench_Lite
difficulty: 15 min - 1 hour
environment_setup_commit: cffd4e0f86fefd4802349a9f9b19ed70934ea354
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-20590:latest
instance_id: sympy__sympy-20590
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.7'
